# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: Ask a Question / Discuss a Topic
    url: https://github.com/bugwarden/nextjs/discussions
    about: Ask questions or discuss topics related to Warden with other users.
  - name: Feature / Documentation Request
    url: https://github.com/bugwarden/nextjs/discussions/new?category=ideas
    about: You may open a feature or documentation request in discussions.
